# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa_geral',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
