# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('produto', '0002_refeicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('1', 'Em Aberto'), ('2', 'Finalizada')], max_length=1)),
                ('metodo', models.CharField(blank=True, choices=[('1', 'Dinheiro'), ('2', 'Cartao Debito'), ('3', 'Cartao Credito')], max_length=1, null=True)),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('desc', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cliente_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='prod_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default='1')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
        ),
        migrations.CreateModel(
            name='refe_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default='1')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('refeicoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.refeicao')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto_item',
            field=models.ManyToManyField(to='pedido.prod_item'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='refeicao_item',
            field=models.ManyToManyField(to='pedido.refe_item'),
        ),
    ]
